### ISSUE TITLE
hard coded /lustre/scratch118 path need to be changed 

### ISSUE THREAD

**Issue by flass** [sanger-pathogens/external-import#45]
https://github.com/sanger-pathogens/external-import/blob/950963f25d8929c350314a772a625ac7b31aafcf/importer/importer.py#L28

example:
```
bsub -o {command.destination}/external_{command.ticket}.%J.%I.o -e {command.destination}/external_{command.ticket}.%J.%I.e -M2000 \\
  -w 'ended("{dependency}")' \\
  -J external_{command.ticket}[1-{length}]%5 -q long \\
  -R "select[mem>2000] rusage[mem=2000]" update_pipeline_from_spreadsheet.pl \\
  -d {command.database} \\
  -f {command.destination} \\
  -p /lustre/scratch118/infgen/pathogen/pathpipe/{command.database}/seq-pipelines \\
  {command.destination}/external_{command.ticket}_\$LSB_JOBINDEX.xls
```

hard coded `/lustre/scratch118` paths in this function need to be changed to `/lustre/scratch125` as a quick fix towards filesystem migration or even better should be relying o an environment variable which we can change through the config file of the farm module

**Comment by Oliver-Lorenz-dev** [comment]
Thanks for raising Florent, this is fixed by #46
